# Generated by Django 3.1.1 on 2020-12-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_debts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Cobrar/Pagar')),
            ],
            options={
                'verbose_name': 'Tipos de cuentas',
                'verbose_name_plural': 'Tipo de cuenta',
                'ordering': ['id'],
            },
        ),
    ]
