# Generated by Django 3.1.1 on 2020-12-03 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_method_pay_providers_type_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Cliente')),
                ('ci', models.CharField(default='V-', max_length=50, unique=True, verbose_name='CI/RIF')),
                ('address', models.CharField(max_length=180, verbose_name='Dirección')),
                ('contact', models.CharField(max_length=50, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolar', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-12-03', max_length=10, verbose_name='Fecha')),
                ('concept', models.CharField(max_length=255, verbose_name='Concepto')),
                ('amount_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto($)')),
                ('amount_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto(Bs.)')),
            ],
            options={
                'verbose_name': 'Ganancia',
                'verbose_name_plural': 'Ganancias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Equipo')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-12-03', max_length=10, verbose_name='Fecha')),
                ('concept', models.CharField(max_length=255, verbose_name='Concepto')),
                ('amount_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto($)')),
                ('amount_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto(Bs.)')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Permisology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Permiso')),
                ('description', models.CharField(max_length=180, verbose_name='Descripción')),
                ('day', models.DateField(default='2020-12-03', max_length=10, verbose_name='Fecha de pago')),
                ('color', models.CharField(default='#007bff', max_length=250, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Permisos y Eventos',
                'verbose_name_plural': 'Permisos y Eventos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Requested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Producto')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Productos Solicitados',
                'verbose_name_plural': 'Productos Solicitados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2020-12-03', max_length=10, verbose_name='Fecha')),
                ('concept', models.CharField(max_length=255, verbose_name='Concepto')),
                ('amount_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto($)')),
                ('amount_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto(Bs.)')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('ci', models.CharField(default='V-', max_length=50, unique=True, verbose_name='C.I.')),
                ('address', models.CharField(max_length=180, verbose_name='Dirección')),
                ('contact', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('admission_date', models.DateField(default='2020-12-03', max_length=10, verbose_name='Ingreso')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Sueldo')),
                ('position', models.CharField(max_length=150, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkerstMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=250, verbose_name='Nota')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipment', verbose_name='Equipo')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.workers', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Mantenimiento por Trabajadores',
                'verbose_name_plural': 'Mantenimientos por Trabajadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejoined', models.DateField(default='2020-12-03', max_length=10, verbose_name='Fecha')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('type_vents', models.CharField(max_length=25, verbose_name='Método')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('desc_discount', models.CharField(max_length=250, verbose_name='Nota')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('description', models.CharField(max_length=250, verbose_name='Nota')),
                ('change', models.CharField(max_length=180, verbose_name='Vuelto pendiente')),
                ('status_change', models.CharField(max_length=180, verbose_name='Estado')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.client')),
                ('method_pay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.method_pay', verbose_name='Método de pago')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product_warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='Código')),
                ('product', models.CharField(max_length=150, verbose_name='Producto')),
                ('brand', models.CharField(max_length=150, verbose_name='Marca')),
                ('description', models.CharField(max_length=180, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio sin IVA')),
                ('price_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio($)')),
                ('price_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio(Bs.)')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad a subir')),
                ('date', models.DateField(default='2020-12-03', max_length=10, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.category', verbose_name='Categoría')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.type_product', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='Código')),
                ('product', models.CharField(max_length=150, verbose_name='Producto')),
                ('brand', models.CharField(max_length=150, verbose_name='Marca')),
                ('description', models.CharField(max_length=180, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio sin IVA')),
                ('price_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='$$')),
                ('price_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Bs.')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('date', models.DateField(default='2020-12-03', max_length=10, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.category', verbose_name='Categoría')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.type_product', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180, verbose_name='Descripción')),
                ('amount_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Costo($$)')),
                ('amount_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Costo(Bs.)')),
                ('pay_date', models.DateField(default='2020-12-03', max_length=10, verbose_name='Fecha')),
                ('next_serv', models.DateField(default='2020-12-03', max_length=10, verbose_name='Próximo Servicio')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipment', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Equipos',
                'verbose_name_plural': 'Mantenimiento de Equipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('quantity', models.IntegerField(default=0)),
                ('sub', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.product_warehouse')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, verbose_name='Proveedor/Cliente')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('start_date', models.DateField(default='2020-12-03', max_length=10, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(default='2020-12-03', max_length=10, verbose_name='Fecha límite')),
                ('dollars', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto ($)')),
                ('bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto (Bs.)')),
                ('type_debts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.type_debts', verbose_name='Cobrar/Pagar')),
            ],
            options={
                'verbose_name': 'Permisos y Eventos',
                'verbose_name_plural': 'Permisos y Eventos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CancelledInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(default='2020-12-03', max_length=10, verbose_name='Fecha')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('image', models.FileField(blank=True, null=True, upload_to='facturas')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.providers', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Factura Cancelada',
                'verbose_name_plural': 'Facturas Canceladas',
                'ordering': ['id'],
            },
        ),
    ]
