# Generated by Django 3.1.1 on 2020-12-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20201205_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(default='2020-12-05', max_length=10, verbose_name='Fecha')),
                ('names', models.CharField(max_length=255, verbose_name='Nombre y Apellido')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('image', models.FileField(blank=True, null=True, upload_to='Cap_Dollars')),
            ],
            options={
                'verbose_name': 'Compra de Dólar',
                'verbose_name_plural': 'Compra de Dólares',
                'ordering': ['id'],
            },
        ),
    ]
