# Generated by Django 3.1.1 on 2020-12-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_dollarpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollarpurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cantidad ($$)'),
        ),
    ]
