# Generated by Django 3.1.1 on 2020-12-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_auto_20201219_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='change',
            field=models.CharField(max_length=180, verbose_name='Vuelto pendiente'),
        ),
    ]
