# Generated by Django 3.1.1 on 2020-12-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_auto_20201220_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='type_vents',
            new_name='type_sale',
        ),
        migrations.AlterField(
            model_name='sale',
            name='iva',
            field=models.DecimalField(decimal_places=2, default='16%', max_digits=30),
        ),
    ]
