# Generated by Django 3.1.1 on 2020-12-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_auto_20201220_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='desc_discount',
            field=models.CharField(default='No aplica', max_length=250, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
