# Generated by Django 3.1.1 on 2021-01-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_auto_20210104_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changescanceled',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Cap_Changes'),
        ),
    ]
