# Generated by Django 3.1.1 on 2021-01-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0022_auto_20210104_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='desc_additional',
            field=models.CharField(default='No aplica', max_length=255, verbose_name='Descripción de Extras'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='desc_discounts',
            field=models.CharField(default='No aplica', max_length=255, verbose_name='Descripción de Descuentos'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='description',
            field=models.CharField(blank=True, default='Sin observaciones', max_length=255, null=True, verbose_name='Observaciones'),
        ),
    ]
