# Generated by Django 3.1.1 on 2021-01-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0024_auto_20210105_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysedes',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Telefono(s)'),
        ),
        migrations.AlterField(
            model_name='companysedes',
            name='postal_zone',
            field=models.CharField(max_length=5, verbose_name='Zona Postal'),
        ),
    ]
