# Generated by Django 3.1.1 on 2021-01-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0025_auto_20210105_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Orden de Entrega',
                'verbose_name_plural': 'Ordenes de Entrega',
                'ordering': ['id'],
            },
        ),
    ]
