# Generated by Django 3.1.1 on 2021-01-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0026_deliveryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='db',
            field=models.CharField(default=2, max_length=255, verbose_name='BD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='number',
            field=models.CharField(max_length=255, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='sale',
            field=models.CharField(max_length=255, verbose_name='Venta'),
        ),
    ]
