# Generated by Django 3.1.1 on 2021-01-08 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0027_auto_20210105_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bubget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejoined', models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('iva', models.DecimalField(decimal_places=2, default='16%', max_digits=30)),
                ('type_sale', models.CharField(max_length=25, verbose_name='Método')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('desc_discount', models.CharField(default='No aplica', max_length=250, verbose_name='Nota')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('total_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('type_received', models.CharField(max_length=25)),
                ('received', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Entrada')),
                ('type_exchange', models.CharField(max_length=25)),
                ('exchange', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cambio')),
                ('description', models.CharField(max_length=250, verbose_name='Nota')),
                ('change', models.CharField(default=0, max_length=180, verbose_name='Vuelto pendiente')),
                ('status_change', models.CharField(max_length=180, verbose_name='Estado')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.client')),
                ('method_pay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.method_pay', verbose_name='Método de pago')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='datejoined',
            field=models.DateField(default='2021-01-08', max_length=10),
        ),
        migrations.AlterField(
            model_name='cancelledinvoices',
            name='pay_date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='changescanceled',
            name='pay_date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='end_date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='start_date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='dollarpurchase',
            name='pay_date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='next_serv',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Próximo Servicio'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='pay_date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='admission_date',
            field=models.DateField(default='2021-01-08', max_length=10, verbose_name='Ingreso'),
        ),
        migrations.CreateModel(
            name='DetBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('quantity', models.IntegerField(default=0)),
                ('sub', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.product_warehouse')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.bubget')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto',
                'verbose_name_plural': 'Detalle de Presupuestos',
                'ordering': ['id'],
            },
        ),
    ]
