# Generated by Django 3.1.1 on 2021-01-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0028_auto_20210108_0004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bubget',
            new_name='Budget',
        ),
    ]
