# Generated by Django 3.1.1 on 2021-01-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0029_auto_20210108_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='detsale',
            name='price_product_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='detsale',
            name='price_product_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='detsale',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='sale',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
