# Generated by Django 3.1.1 on 2021-01-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0031_auto_20210108_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detbudget',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio del Producto S/IVA'),
        ),
        migrations.AlterField(
            model_name='detbudget',
            name='price_product_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio del Producto en Bs.'),
        ),
        migrations.AlterField(
            model_name='detbudget',
            name='price_product_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio del Producto en $'),
        ),
        migrations.AlterField(
            model_name='detbudget',
            name='rate',
            field=models.DecimalField(decimal_places=22, default=0.0, max_digits=30, verbose_name='Tasa $ Calculada'),
        ),
        migrations.AlterField(
            model_name='detbudget',
            name='sub',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Subtotal C/IVA'),
        ),
        migrations.AlterField(
            model_name='detbudget',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Subtotal S/IVA'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio del Producto S/IVA'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='price_product_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio del Producto en Bs.'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='price_product_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio del Producto en $'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Tasa $ Calculada'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='sub',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Subtotal C/IVA'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Subtotal S/IVA'),
        ),
    ]
