# Generated by Django 3.1.1 on 2021-01-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0032_auto_20210108_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total Sin/Descuento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.CharField(default='00000000', max_length=255, verbose_name='Número de guía'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total Sin/Descuento'),
        ),
    ]
