# Generated by Django 3.1.1 on 2021-01-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0033_auto_20210108_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_sale_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total $$ Sin/Descuento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_sale_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total $$ Sin/Descuento'),
        ),
    ]
