# Generated by Django 3.1.1 on 2021-01-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0034_auto_20210108_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='datejoined',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cancelledinvoices',
            name='pay_date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='changescanceled',
            name='pay_date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='end_date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='start_date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='datejoined',
            field=models.DateField(default='2021-01-11', max_length=10),
        ),
        migrations.AlterField(
            model_name='dollarpurchase',
            name='pay_date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='next_serv',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Próximo Servicio'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='pay_date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='admission_date',
            field=models.DateField(default='2021-01-11', max_length=10, verbose_name='Ingreso'),
        ),
        migrations.CreateModel(
            name='MovingProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejoined', models.DateField(default='2021-01-11, 00:00:00', max_length=50, verbose_name='Fecha')),
                ('description', models.CharField(max_length=250, verbose_name='Notas y/o Descripción')),
                ('order', models.CharField(default='00000000', max_length=255, verbose_name='Número de guía')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.companysedes')),
            ],
            options={
                'verbose_name': 'Traslado de Bienes',
                'verbose_name_plural': 'Traslado de Bienes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetMovingProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_product_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio del Producto en $')),
                ('quantity', models.IntegerField(default=0)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.movingproducts')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.product')),
            ],
            options={
                'verbose_name': 'Detalle de Traslado de Bienes',
                'ordering': ['id'],
            },
        ),
    ]
