# Generated by Django 3.1.1 on 2021-01-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0041_auto_20210114_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeGuideOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejoined', models.DateField(default='2021-01-14', max_length=10)),
                ('transfer', models.CharField(max_length=255, verbose_name='Venta')),
                ('db', models.CharField(max_length=255, verbose_name='BD')),
                ('number', models.CharField(max_length=255, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Guía de Despacho',
                'verbose_name_plural': 'Guías de Despachos',
                'ordering': ['id'],
            },
        ),
    ]
