# Generated by Django 3.1.1 on 2021-01-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0042_officeguideorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='db',
        ),
        migrations.RemoveField(
            model_name='officeguideorder',
            name='db',
        ),
        migrations.RemoveField(
            model_name='officeguideorder',
            name='transfer',
        ),
        migrations.AddField(
            model_name='officeguideorder',
            name='move',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crud.movingproducts', verbose_name='MovingProductsId'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.movingproducts', verbose_name='SaleId'),
        ),
    ]
