# Generated by Django 3.1.1 on 2021-01-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0043_auto_20210114_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.sale', verbose_name='SaleId'),
        ),
    ]
