# Generated by Django 3.1.1 on 2021-01-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0045_auto_20210114_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeguideorder',
            name='datejoined',
            field=models.DateField(default='2021-01-14 HH:mm a', max_length=10),
        ),
    ]
