# Generated by Django 3.1.1 on 2021-01-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0047_auto_20210114_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeguideorder',
            name='datejoined',
            field=models.DateField(default='2021-01-14 00:01 AM', max_length=10),
        ),
    ]
