# Generated by Django 3.1.1 on 2021-01-15 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0054_auto_20210114_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeguideorder',
            name='move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.movingproducts', verbose_name='MovingProductsId'),
        ),
    ]
