# Generated by Django 3.1.1 on 2021-01-15 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0055_auto_20210114_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='detmovingproducts',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='movingproducts',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.sale', verbose_name='SaleId'),
        ),
        migrations.AlterField(
            model_name='detmovingproducts',
            name='price_product_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio en $'),
        ),
        migrations.AlterField(
            model_name='movingproducts',
            name='datejoined',
            field=models.DateField(default='2021-01-14', max_length=10, verbose_name='Fecha'),
        ),
    ]
