# Generated by Django 3.1.1 on 2021-01-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0057_auto_20210115_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movingproducts',
            name='description',
            field=models.CharField(default='Ninguna', max_length=250, verbose_name='Notas y/o Descripción'),
        ),
    ]
