# Generated by Django 3.1.1 on 2021-01-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0060_auto_20210122_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='type_exchange',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='type_received',
        ),
    ]
