# Generated by Django 3.1.1 on 2021-01-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0061_auto_20210122_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='type_exchange',
            field=models.CharField(default='$', max_length=15, verbose_name='Símbolo del cambio'),
        ),
    ]
