# Generated by Django 3.1.1 on 2021-01-22 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0062_sale_type_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='method_pay1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_pay1', to='crud.method_pay', verbose_name='Método de pago (2)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='method_pay2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_pay2', to='crud.method_pay', verbose_name='Método de pago (3)'),
        ),
    ]
