# Generated by Django 3.1.1 on 2021-01-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0063_auto_20210122_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='method_pay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crud.method_pay', verbose_name='Método de pago (1)'),
        ),
    ]
