# Generated by Django 3.1.1 on 2021-01-24 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0065_auto_20210122_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='datejoined',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cancelledinvoices',
            name='pay_date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='changescanceled',
            name='pay_date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='end_date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='start_date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='datejoined',
            field=models.DateField(default='2021-01-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='dollarpurchase',
            name='pay_date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='next_serv',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Próximo Servicio'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='pay_date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movingproducts',
            name='datejoined',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='officeguideorder',
            name='datejoined',
            field=models.DateField(default='2021-01-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='method_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='method_pays', to='crud.method_pay', verbose_name='Método de pago (1)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='method_pay1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_pays1', to='crud.method_pay', verbose_name='Método de pago (2)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='method_pay2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_pays2', to='crud.method_pay', verbose_name='Método de pago (3)'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='admission_date',
            field=models.DateField(default='2021-01-24', max_length=10, verbose_name='Ingreso'),
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(default='00000000', max_length=255, verbose_name='Factura Nº')),
                ('datejoined', models.DateField(default='2021-01-24', max_length=10, verbose_name='Fecha')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('iva', models.DecimalField(decimal_places=2, default='16%', max_digits=30)),
                ('type_sale', models.CharField(max_length=25, verbose_name='Método')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('desc_discount', models.CharField(default='No aplica', max_length=250, verbose_name='Nota')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('total_sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total Sin/Descuento')),
                ('total_sale_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total $$ Sin/Descuento')),
                ('total_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('received', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Entrada (1)')),
                ('received1', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Entrada (2)')),
                ('received2', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Entrada (3)')),
                ('exchange', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cambio')),
                ('type_exchange', models.CharField(default='$', max_length=15, verbose_name='Símbolo del cambio')),
                ('description', models.CharField(max_length=250, verbose_name='Nota')),
                ('change', models.CharField(default=0, max_length=180, verbose_name='Vuelto pendiente')),
                ('status_change', models.CharField(max_length=180, verbose_name='Estado')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('order', models.CharField(default='00000000', max_length=255, verbose_name='Número de guía')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.client')),
                ('method_pay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='method_pay_sr', to='crud.method_pay', verbose_name='Método de pago (1)')),
                ('method_pay1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_pay_sr1', to='crud.method_pay', verbose_name='Método de pago (2)')),
                ('method_pay2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_pay_sr2', to='crud.method_pay', verbose_name='Método de pago (3)')),
                ('prevSale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.sale')),
            ],
            options={
                'verbose_name': 'Venta por Devolución',
                'verbose_name_plural': 'Ventas por Devoluciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetSaleReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_product_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio del Producto en Bs.')),
                ('price_product_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio del Producto en $')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio del Producto S/IVA')),
                ('quantity', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Subtotal S/IVA')),
                ('sub', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Subtotal C/IVA')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Tasa $ Calculada')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.product_warehouse')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.salereturn')),
            ],
            options={
                'verbose_name': 'Detalle de Venta por Devolución',
                'verbose_name_plural': 'Detalle de Ventas por Devoluciones',
                'ordering': ['id'],
            },
        ),
    ]
