# Generated by Django 3.1.1 on 2021-01-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0067_auto_20210130_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='type_exchange',
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cambio'),
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cambio'),
        ),
    ]
