# Generated by Django 3.1.1 on 2021-02-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0070_auto_20210201_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='method_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_pays', to='crud.method_pay', verbose_name='Método de pago (1)'),
        ),
    ]
