# Generated by Django 3.1.1 on 2021-02-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0072_auto_20210201_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changescanceled',
            name='names',
            field=models.CharField(max_length=255, verbose_name='Datos del Cliente (Nombre, Apellido, CI)'),
        ),
    ]
