# Generated by Django 3.1.1 on 2021-02-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0073_auto_20210201_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(default='00000000', max_length=255, verbose_name='Nota de Crédito Nº')),
                ('invoice_number', models.CharField(default='00000000', max_length=255, verbose_name='Factura Nº')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('status', models.IntegerField(default=0, verbose_name='Estado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.client')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.sale')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['id'],
            },
        ),
    ]
