# Generated by Django 3.1.1 on 2021-02-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0075_budget_budget_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotes',
            name='datejoined',
            field=models.DateField(default='2021-02-01', max_length=10, verbose_name='Fecha'),
        ),
    ]
