# Generated by Django 3.1.1 on 2021-02-01 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0076_creditnotes_datejoined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotes',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.client'),
        ),
        migrations.AlterField(
            model_name='creditnotes',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.sale'),
        ),
    ]
