# Generated by Django 3.1.1 on 2021-02-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0078_auto_20210202_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledinvoices',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cantidad ($$)'),
        ),
    ]
