# Generated by Django 3.1.1 on 2021-02-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0080_auto_20210204_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banktransfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNumber', models.CharField(max_length=30, verbose_name='Número de Referencia')),
                ('bank', models.CharField(max_length=30, verbose_name='Banco')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto')),
                ('description', models.CharField(max_length=180, verbose_name='Notas y/o Descripción')),
                ('image', models.FileField(blank=True, null=True, upload_to='Cap_Banktransfers')),
            ],
            options={
                'verbose_name': 'Transferencias Bancarias',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
    ]
