# Generated by Django 3.1.1 on 2021-02-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0081_auto_20210204_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfers',
            name='pay_date',
            field=models.DateField(default='2021-02-04', max_length=10, verbose_name='Fecha'),
        ),
    ]
