# Generated by Django 3.1.1 on 2021-02-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0083_bankaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfers',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.workers', verbose_name='Banco'),
        ),
    ]
