# Generated by Django 3.1.1 on 2021-02-04 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0084_auto_20210204_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfers',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.bankaccounts', verbose_name='Banco'),
        ),
    ]
