# Generated by Django 3.1.1 on 2021-02-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0091_auto_20210205_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ci',
            field=models.CharField(max_length=50, unique=True, verbose_name='CI/RIF'),
        ),
    ]
