# Generated by Django 3.1.1 on 2021-02-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0092_auto_20210205_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='desc_discounts',
            field=models.CharField(default='No aplica', max_length=255, verbose_name='Descripción de Deducciones'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='discounts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Deducciones'),
        ),
    ]
