# Generated by Django 3.1.1 on 2021-02-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0094_auto_20210206_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='amount_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Costo|Mantenimiento($$)'),
        ),
    ]
