# Generated by Django 3.1.1 on 2021-02-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0097_auto_20210206_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstmaintenance',
            name='next_serv',
            field=models.DateField(default='2021-02-06', max_length=10, verbose_name='Próximo Servicio'),
        ),
        migrations.AddField(
            model_name='workerstmaintenance',
            name='pay_date',
            field=models.DateField(default='2021-02-06', max_length=10, verbose_name='Fecha'),
        ),
    ]
