# Generated by Django 3.1.1 on 2021-02-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0102_auto_20210206_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Sueldo (Bs.)'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Sueldo ($$)'),
        ),
    ]
