# Generated by Django 3.1.1 on 2021-02-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0106_auto_20210208_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledinvoices',
            name='provider',
            field=models.CharField(max_length=255, verbose_name='Proveedor/Cliente'),
        ),
    ]
