# Generated by Django 3.1.1 on 2021-02-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0108_auto_20210212_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(default='2021-02-12', max_length=10, verbose_name='Fecha')),
                ('provider', models.CharField(max_length=255, verbose_name='Proveedor/Cliente')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cantidad ($$)')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('image', models.FileField(blank=True, null=True, upload_to='Cap_Payments')),
            ],
            options={
                'verbose_name': 'Abono de Factura',
                'verbose_name_plural': 'Abonos de Facturas',
                'ordering': ['id'],
            },
        ),
    ]
