# Generated by Django 3.1.1 on 2021-02-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0110_auto_20210212_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Abono|$$'),
        ),
    ]
