# Generated by Django 3.1.1 on 2021-02-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0112_auto_20210212_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='detsale',
            name='subtotal_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Subtotal $ S/IVA'),
        ),
        migrations.AlterField(
            model_name='banktransfers',
            name='pay_date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='datejoined',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cancelledinvoices',
            name='pay_date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='changescanceled',
            name='pay_date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='creditnotes',
            name='datejoined',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='end_date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='start_date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='datejoined',
            field=models.DateField(default='2021-02-13', max_length=10),
        ),
        migrations.AlterField(
            model_name='dollarpurchase',
            name='pay_date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='next_serv',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Próximo Servicio'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='pay_date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movingproducts',
            name='date_end',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha|Vencimiento'),
        ),
        migrations.AlterField(
            model_name='movingproducts',
            name='datejoined',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha|Traslado'),
        ),
        migrations.AlterField(
            model_name='officeguideorder',
            name='datejoined',
            field=models.DateField(default='2021-02-13', max_length=10),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay_date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='admission_date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Ingreso'),
        ),
        migrations.AlterField(
            model_name='workerstmaintenance',
            name='next_serv',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Próximo Servicio'),
        ),
        migrations.AlterField(
            model_name='workerstmaintenance',
            name='pay_date',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha'),
        ),
    ]
