# Generated by Django 3.1.1 on 2021-02-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0113_auto_20210213_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='date_end',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha|Vencimiento'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='datejoined',
            field=models.DateField(default='2021-02-13', max_length=10, verbose_name='Fecha|Traslado'),
        ),
    ]
