# Generated by Django 3.1.1 on 2021-02-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0115_auto_20210214_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changescanceled',
            name='names',
            field=models.CharField(max_length=255, verbose_name='Datos del Cliente'),
        ),
    ]
