# Generated by Django 3.1.1 on 2021-02-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0118_auto_20210220_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='equipment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='crud.equipment', verbose_name='Equipo'),
            preserve_default=False,
        ),
    ]
