# Generated by Django 3.1.1 on 2021-02-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0119_auto_20210220_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipment', verbose_name='Equipo'),
        ),
    ]
