# Generated by Django 3.1.1 on 2021-03-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0126_auto_20210226_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangesCanceled',
        ),
        migrations.RemoveField(
            model_name='detmovingproducts',
            name='move',
        ),
        migrations.RemoveField(
            model_name='detmovingproducts',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='equipmentmaintenance',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='movingproducts',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='movingproducts',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='movingproducts',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='officeguideorder',
            name='move',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='workerstmaintenance',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='workerstmaintenance',
            name='worker',
        ),
        migrations.AlterField(
            model_name='banktransfers',
            name='pay_date',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='datejoined',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cancelledinvoices',
            name='pay_date',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='end_date',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='start_date',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='date_end',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha|Vencimiento'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='datejoined',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha|Traslado'),
        ),
        migrations.AlterField(
            model_name='dollarpurchase',
            name='pay_date',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='date',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay_date',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='date',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateField(default='2021-03-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.DeleteModel(
            name='CreditNotes',
        ),
        migrations.DeleteModel(
            name='DetMovingProducts',
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='EquipmentMaintenance',
        ),
        migrations.DeleteModel(
            name='MovingProducts',
        ),
        migrations.DeleteModel(
            name='OfficeGuideOrder',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
        migrations.DeleteModel(
            name='WorkerstMaintenance',
        ),
    ]
