# Generated by Django 3.1.1 on 2021-03-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0127_auto_20210301_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Producto (Stock 1)', 'verbose_name_plural': 'Productos (Stock 1)'},
        ),
        migrations.AlterModelOptions(
            name='product_warehouse',
            options={'ordering': ['id'], 'verbose_name': 'Producto (Stock 2)', 'verbose_name_plural': 'Productos (Stock 2)'},
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='price_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Bs.'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='price_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='$$'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
