# Generated by Django 3.1.1 on 2021-03-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0128_auto_20210301_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DollarPurchase',
        ),
    ]
