# Generated by Django 3.1.1 on 2021-03-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0129_delete_dollarpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=10, unique=True, verbose_name='Identificación')),
            ],
            options={
                'verbose_name': 'Tipo de identificación',
                'verbose_name_plural': 'Tipos de identificación',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='banktransfers',
            name='pay_date',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='datejoined',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cancelledinvoices',
            name='pay_date',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='end_date',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='start_date',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='date_end',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha|Vencimiento'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='datejoined',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha|Traslado'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='date',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay_date',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='date',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha'),
        ),
    ]
