# Generated by Django 3.1.1 on 2021-03-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0130_auto_20210321_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identity',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='crud.id_type', verbose_name='Identificación'),
        ),
        migrations.AddField(
            model_name='providers',
            name='identity',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='crud.id_type', verbose_name='Identificación'),
        ),
    ]
