# Generated by Django 3.1.1 on 2021-03-21 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0131_auto_20210321_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejoined', models.CharField(default='2021-03-21', max_length=30, verbose_name='Fecha')),
                ('rate_dolar1', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Tasa general')),
                ('rate_dolar2', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Tasa descuentos')),
            ],
            options={
                'verbose_name': 'Historial (Dólar)',
                'verbose_name_plural': 'Historial (Dólar)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DollarPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha')),
                ('names', models.CharField(max_length=255, verbose_name='Nombre y Apellido')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cantidad ($$)')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('image', models.FileField(blank=True, null=True, upload_to='Cap_Dollars')),
            ],
            options={
                'verbose_name': 'Compra de Dólar',
                'verbose_name_plural': 'Compra de Dólares',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Producto (Almacén)', 'verbose_name_plural': 'Productos (Almacén)'},
        ),
        migrations.AlterModelOptions(
            name='product_warehouse',
            options={'ordering': ['id'], 'verbose_name': 'Producto (Venta)', 'verbose_name_plural': 'Productos (Ventas)'},
        ),
        migrations.AddField(
            model_name='detsale',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Ganancia'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio|Costo'),
        ),
        migrations.AddField(
            model_name='product',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Ganancia'),
        ),
        migrations.AddField(
            model_name='product_warehouse',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio|Costo'),
        ),
        migrations.AddField(
            model_name='product_warehouse',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Ganancia'),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Vuelto|Descontado'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='type_debts',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='crud.type_debts', verbose_name='Cobrar/Pagar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio|Venta'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='price_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio(Bs.)'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='price_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio|Venta'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad a subir'),
        ),
        migrations.CreateModel(
            name='HistoryOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejoined', models.CharField(default='2021-03-21', max_length=30, verbose_name='Fecha')),
                ('description', models.CharField(max_length=2255, verbose_name='Descripción')),
                ('userSession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Operaciones',
                'verbose_name_plural': 'Historial de Operaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CreditNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejoined', models.DateField(default='2021-03-21', max_length=10, verbose_name='Fecha')),
                ('credit_note_number', models.CharField(default='00000000', max_length=255, verbose_name='Nota de Crédito Nº')),
                ('invoice_number', models.CharField(default='00000000', max_length=255, verbose_name='Generada en Factura Nº')),
                ('invoice_apply', models.CharField(default='00000000', max_length=255, verbose_name='Aplicada en Factura Nº')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('status', models.IntegerField(default=0, verbose_name='Estado')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.client')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.sale')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['id'],
            },
        ),
    ]
