# Generated by Django 3.1.1 on 2021-03-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0132_auto_20210321_0336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DollarPurchase',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Producto (Stock1)', 'verbose_name_plural': 'Productos (Stock1)'},
        ),
        migrations.AlterModelOptions(
            name='product_warehouse',
            options={'ordering': ['id'], 'verbose_name': 'Producto (Stock2)', 'verbose_name_plural': 'Productos (Stock2)'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='change',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='change_discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='status_change',
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='price_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Bs.'),
        ),
        migrations.AlterField(
            model_name='product_warehouse',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
