# Generated by Django 3.1.1 on 2021-03-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0137_auto_20210322_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='detbudget',
            name='subtotal_dl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Subtotal $ S/IVA'),
        ),
    ]
