# Generated by Django 3.1.1 on 2021-03-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0140_invoices_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='invoices'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Products'),
        ),
    ]
