# Generated by Django 3.1.1 on 2021-03-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0141_auto_20210322_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='image',
        ),
    ]
