# Generated by Django 3.1.1 on 2021-03-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0143_auto_20210322_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='banktransfers',
            name='pay_date',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='datejoined',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cancelledinvoices',
            name='pay_date',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='creditnotes',
            name='datejoined',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='end_date',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='start_date',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='date_end',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha|Vencimiento'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='datejoined',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha|Traslado'),
        ),
        migrations.AlterField(
            model_name='dollarhistory',
            name='datejoined',
            field=models.CharField(default='2021-03-23', max_length=30, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='date',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historyoperations',
            name='datejoined',
            field=models.CharField(default='2021-03-23', max_length=30, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='datejoined',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay_date',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateField(default='2021-03-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.CreateModel(
            name='DetInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio|Unitario')),
                ('shipment', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='%|Envío')),
                ('gain', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='%|Ganancia')),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio|Final')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.invoices')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.product')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalle de Facturas',
                'ordering': ['id'],
            },
        ),
    ]
