# Generated by Django 3.1.1 on 2021-03-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0145_auto_20210324_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='description',
        ),
        migrations.AddField(
            model_name='invoices',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
