# Generated by Django 3.1.1 on 2021-03-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0146_auto_20210324_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
