# Generated by Django 3.1.1 on 2021-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0149_auto_20210325_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='number_invoice',
            field=models.CharField(default='00000000', max_length=255, verbose_name='Compra Nº'),
        ),
    ]
