# Generated by Django 3.1.1 on 2021-03-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0152_remove_dollarhistory_rate_dolar2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
