# Generated by Django 3.1.1 on 2021-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0153_delete_deliveryorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='control_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='credit_note',
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(default='00000000', max_length=255, verbose_name='Nº Venta'),
        ),
    ]
