# Generated by Django 3.1.1 on 2021-03-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0155_auto_20210325_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detinvoices',
            name='prod',
        ),
        migrations.AddField(
            model_name='detinvoices',
            name='category',
            field=models.CharField(default=2, max_length=150, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detinvoices',
            name='code',
            field=models.CharField(default=2, max_length=150, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detinvoices',
            name='product',
            field=models.CharField(default=2, max_length=150, verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detinvoices',
            name='type_product',
            field=models.CharField(default=2, max_length=150, verbose_name='Tipo de Producto'),
            preserve_default=False,
        ),
    ]
