# Generated by Django 3.1.1 on 2021-03-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0156_auto_20210325_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditNotes',
        ),
    ]
