# Generated by Django 3.1.1 on 2021-03-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0157_delete_creditnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Tipos de servicios',
                'verbose_name_plural': 'Tipo de servicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejoined', models.DateField(default='2021-03-25', max_length=10, verbose_name='Fecha')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('amount_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto|$')),
                ('amount_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto|Bs.')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.type_services', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['id'],
            },
        ),
    ]
