# Generated by Django 3.1.6 on 2021-05-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0160_auto_20210504_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.CharField(default='00000000', max_length=255, verbose_name='Pedido Nº')),
                ('datejoined', models.DateField(default='2021-05-04', max_length=10, verbose_name='Fecha')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
            ],
            options={
                'verbose_name': 'Pedidos',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='invoices',
            name='number_invoice',
            field=models.CharField(default='00000000', max_length=255, verbose_name='Factura Nº'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='crud.orders'),
            preserve_default=False,
        ),
    ]
