# Generated by Django 3.1.6 on 2021-05-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0161_auto_20210504_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='amount_bs',
        ),
        migrations.RemoveField(
            model_name='services',
            name='amount_dl',
        ),
        migrations.AddField(
            model_name='services',
            name='amount1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='services',
            name='amount2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto|%'),
        ),
        migrations.AddField(
            model_name='services',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Ganancia'),
        ),
    ]
