# Generated by Django 3.1.6 on 2021-05-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0163_auto_20210518_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
