# Generated by Django 3.1.6 on 2021-05-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0164_orders_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detinvoices',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='detinvoices',
            name='type_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.type_product', verbose_name='Tipo de Producto'),
        ),
    ]
