# Generated by Django 3.1.6 on 2021-05-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0165_auto_20210518_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detinvoices',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='detinvoices',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.type_product', verbose_name='Tipo de Producto'),
        ),
    ]
