# Generated by Django 3.1.6 on 2021-05-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0166_auto_20210518_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Estado'),
        ),
    ]
