# Generated by Django 3.1.6 on 2021-05-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0167_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfers',
            name='pay_date',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='banktransfers',
            name='referenceNumber',
            field=models.CharField(max_length=50, verbose_name='Número de Referencia'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='datejoined',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='type_sale',
            field=models.CharField(max_length=50, verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='cancelledinvoices',
            name='pay_date',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(max_length=255, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='names',
            field=models.CharField(max_length=255, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='companysedes',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='companysedes',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Telefono(s)'),
        ),
        migrations.AlterField(
            model_name='companysedes',
            name='postal_zone',
            field=models.CharField(max_length=10, verbose_name='Zona Postal'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='end_date',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='start_date',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='detinvoices',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='detinvoices',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='date',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='contact',
            field=models.CharField(max_length=250, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='names',
            field=models.CharField(max_length=255, verbose_name='Facilitador'),
        ),
        migrations.AlterField(
            model_name='historyoperations',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='datejoined',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='method_pay',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='datejoined',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay_date',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=250, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=250, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='contact',
            field=models.CharField(max_length=255, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='requested',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='requested',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='type_sale',
            field=models.CharField(max_length=100, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='services',
            name='datejoined',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateField(default='2021-05-18', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='type_debts',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Cobrar/Pagar'),
        ),
        migrations.AlterField(
            model_name='type_product',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='type_services',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Servicio'),
        ),
    ]
