# Generated by Django 3.1.6 on 2021-05-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0168_auto_20210518_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identity',
            field=models.CharField(choices=[('1', 'v'), ('2', 'E'), ('3', 'J'), ('4', 'G'), ('5', 'P'), ('6', 'M')], default=1, max_length=2),
        ),
    ]
