# Generated by Django 3.1.6 on 2021-05-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0172_auto_20210518_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default=1, max_length=2),
        ),
        migrations.DeleteModel(
            name='Product_group',
        ),
    ]
