# Generated by Django 3.1.6 on 2021-05-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0173_auto_20210518_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='identity',
            field=models.CharField(choices=[('V', 'V'), ('E', 'E'), ('J', 'J'), ('G', 'G'), ('P', 'P'), ('M', 'M')], default='V', max_length=2),
        ),
        migrations.AlterField(
            model_name='providers',
            name='identity',
            field=models.CharField(choices=[('V', 'V'), ('E', 'E'), ('J', 'J'), ('G', 'G'), ('P', 'P'), ('M', 'M')], default='V', max_length=2),
        ),
        migrations.DeleteModel(
            name='Id_Type',
        ),
    ]
