# Generated by Django 3.1.6 on 2021-05-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0176_auto_20210518_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debts',
            name='rate',
        ),
    ]
