# Generated by Django 3.1.6 on 2021-05-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0178_auto_20210528_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('identity', models.CharField(choices=[('V', 'V'), ('E', 'E'), ('J', 'J'), ('G', 'G'), ('P', 'P'), ('M', 'M')], default='V', max_length=2)),
                ('nit', models.CharField(max_length=50, verbose_name='RIF')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('contact', models.CharField(max_length=255, verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentsBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca de equipo',
                'verbose_name_plural': 'Marcas de equipo',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Modelo de Equipo',
                'verbose_name_plural': 'Modelos de Equipos',
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveField(
            model_name='banktransfers',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='cli',
        ),
        migrations.RemoveField(
            model_name='cancelledinvoices',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Debts',
        ),
        migrations.RemoveField(
            model_name='detbudget',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='detbudget',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='detinvoices',
            name='category',
        ),
        migrations.RemoveField(
            model_name='detinvoices',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='detinvoices',
            name='type_product',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='sale',
        ),
        migrations.DeleteModel(
            name='Dolar',
        ),
        migrations.DeleteModel(
            name='DollarHistory',
        ),
        migrations.DeleteModel(
            name='Earnings',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.RemoveField(
            model_name='historyoperations',
            name='userSession',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='order',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_product',
        ),
        migrations.DeleteModel(
            name='Requested',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cli',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='method_pay',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='method_pay1',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='method_pay2',
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
        migrations.RemoveField(
            model_name='services',
            name='amount1',
        ),
        migrations.RemoveField(
            model_name='services',
            name='amount2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='gain',
        ),
        migrations.RemoveField(
            model_name='services',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='services',
            name='type_service',
        ),
        migrations.AddField(
            model_name='services',
            name='code',
            field=models.CharField(default=2, max_length=250, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default=2, max_length=250, verbose_name='Horas Trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='delivery_time',
            field=models.DateField(default='2021-05-29', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_anomaly',
            field=models.TextField(default=2, verbose_name='Anomalía'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_date',
            field=models.DateField(default='2021-05-29', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_location',
            field=models.CharField(default=2, max_length=250, verbose_name='Ubicación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_others',
            field=models.CharField(default=2, max_length=250, verbose_name='Otros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_received',
            field=models.CharField(default=2, max_length=255, verbose_name='Recibido por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_reference',
            field=models.CharField(default=2, max_length=250, verbose_name='Referencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_reported',
            field=models.CharField(default=2, max_length=255, verbose_name='Reportado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_serie',
            field=models.CharField(default=2, max_length=250, verbose_name='Serie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_service',
            field=models.IntegerField(default=0, verbose_name='Tipo dPRODUCT_GROUPS_CHOICEe Mantenimiento'),
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_work_hours',
            field=models.CharField(default=2, max_length=250, verbose_name='Horas Trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='number_version',
            field=models.CharField(default=2, max_length=250, verbose_name='Version Nº'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='observations',
            field=models.TextField(default=2, verbose_name='Repuestos utilizados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='report_number',
            field=models.CharField(default='00000000', max_length=255, verbose_name='Consecutivo'),
        ),
        migrations.AddField(
            model_name='services',
            name='service_details',
            field=models.TextField(default=2, verbose_name='Detalles del Servicio Técnico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='service_received',
            field=models.CharField(default=2, max_length=255, verbose_name='Reportado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='service_reported',
            field=models.CharField(default=2, max_length=255, verbose_name='Reportado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='spare_parts',
            field=models.TextField(default=2, verbose_name='Repuestos utilizados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-05-29', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='services',
            name='datejoined',
            field=models.DateField(default='2021-05-29', max_length=50, verbose_name='Fecha'),
        ),
        migrations.DeleteModel(
            name='BankAccounts',
        ),
        migrations.DeleteModel(
            name='Banktransfers',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='CancelledInvoices',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='DetBudget',
        ),
        migrations.DeleteModel(
            name='DetInvoices',
        ),
        migrations.DeleteModel(
            name='DetSale',
        ),
        migrations.DeleteModel(
            name='Facilitator',
        ),
        migrations.DeleteModel(
            name='HistoryOperations',
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
        migrations.DeleteModel(
            name='Method_pay',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Providers',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Type_product',
        ),
        migrations.DeleteModel(
            name='Type_services',
        ),
        migrations.AddField(
            model_name='services',
            name='business',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crud.business', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crud.equipments', verbose_name='Equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_brand',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentsbrand', verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_model',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentsmodels', verbose_name='Modelo'),
            preserve_default=False,
        ),
    ]
