# Generated by Django 3.1.6 on 2021-05-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0179_auto_20210529_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-05-29', max_length=50, verbose_name='Fecha'),
        ),
    ]
