# Generated by Django 3.1.6 on 2021-05-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0181_auto_20210529_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='equipment_service',
            field=models.IntegerField(default=0, verbose_name='Tipo de Mantenimiento'),
        ),
    ]
