# Generated by Django 3.1.6 on 2021-05-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0182_auto_20210529_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='nit',
            field=models.CharField(max_length=50, verbose_name='NIT'),
        ),
    ]
