# Generated by Django 3.1.6 on 2021-05-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0183_auto_20210529_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='identity',
        ),
    ]
