# Generated by Django 3.1.6 on 2021-05-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0184_remove_business_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='datejoined',
            field=models.DateField(default='2021-05-29', max_length=50, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(max_length=250, verbose_name='Hora de entrega'),
        ),
    ]
