# Generated by Django 3.1.6 on 2021-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0185_auto_20210529_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-05-29, 00:00:00', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
