# Generated by Django 3.1.6 on 2021-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0187_auto_20210529_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='equipment_service',
            field=models.CharField(choices=[('PREVENTIVO', 'PREVENTIVO'), ('CORRECTIVO', 'CORRECTIVO')], default='PREVENTIVO', max_length=20, verbose_name='Tipo de Mantenimiento'),
        ),
    ]
