# Generated by Django 3.1.6 on 2021-05-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0188_auto_20210529_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='observations',
            field=models.TextField(verbose_name='Observaciones'),
        ),
    ]
