# Generated by Django 3.1.6 on 2021-05-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0189_auto_20210529_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_time',
            field=models.DateField(default='2021-05-29', max_length=50, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_received',
            field=models.CharField(max_length=255, verbose_name='Recibido por'),
        ),
    ]
