# Generated by Django 3.1.6 on 2021-05-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0191_auto_20210529_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='2021-05-29 | 14:48:01 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
    ]
