# Generated by Django 3.1.6 on 2021-05-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0192_auto_20210529_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='14:49:35 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-05-29 14:49:35 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
