# Generated by Django 3.1.6 on 2021-05-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0193_auto_20210529_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='consecutive',
            field=models.CharField(default='000', max_length=255, verbose_name='Secuencia'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='22:05:14 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-05-29 22:05:13 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='services',
            name='report_number',
            field=models.CharField(default='000', max_length=255, verbose_name='Consecutivo'),
        ),
    ]
