# Generated by Django 3.1.6 on 2021-06-21 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0194_auto_20210529_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejoined', models.DateField(default='2021-06-20', max_length=50, verbose_name='Fecha')),
                ('code', models.CharField(max_length=100, verbose_name='Código')),
                ('version', models.CharField(max_length=100, verbose_name='Versión')),
                ('objective', models.CharField(max_length=255, verbose_name='Objetivo')),
                ('made_by', models.CharField(max_length=100, verbose_name='Realizado')),
                ('period', models.CharField(max_length=150, verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Mantenimiento Hospitalario',
                'verbose_name_plural': 'Mantenimientos Hospitalarios',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-06-20', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='services',
            name='datejoined',
            field=models.DateField(default='2021-06-20', max_length=50, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='21:32:20 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_time',
            field=models.DateField(default='2021-06-20', max_length=50, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-20 21:32:20 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
        migrations.CreateModel(
            name='DetMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(default=0)),
                ('serial', models.CharField(max_length=100, verbose_name='Serial')),
                ('period', models.CharField(choices=[('TRIMESTRAL', 'TRIMESTRAL'), ('SEMESTRAL', 'SEMESTRAL'), ('ANUAL', 'ANUAL')], default='TRIMESTRAL', max_length=50, verbose_name='Período')),
                ('january', models.IntegerField(default=0, verbose_name='Enero')),
                ('february', models.IntegerField(default=0, verbose_name='Febrero')),
                ('march', models.IntegerField(default=0, verbose_name='Marzo')),
                ('april', models.IntegerField(default=0, verbose_name='Abril')),
                ('may', models.IntegerField(default=0, verbose_name='Mayo')),
                ('june', models.IntegerField(default=0, verbose_name='Junio')),
                ('july', models.IntegerField(default=0, verbose_name='Julio')),
                ('august', models.IntegerField(default=0, verbose_name='Agosto')),
                ('september', models.IntegerField(default=0, verbose_name='Septiembre')),
                ('october', models.IntegerField(default=0, verbose_name='Octubre')),
                ('november', models.IntegerField(default=0, verbose_name='Noviembre')),
                ('december', models.IntegerField(default=0, verbose_name='Diciembre')),
                ('representative', models.CharField(max_length=150, verbose_name='Representante')),
                ('activities', models.TextField(verbose_name='Actividades a realizar')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipments', verbose_name='Equipo')),
                ('equipmentBrand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentsbrand', verbose_name='Marca')),
                ('equipmentModels', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentsmodels', verbose_name='Modelo')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.maintenance')),
            ],
            options={
                'verbose_name': 'Detalle de Mantenimiento',
                'verbose_name_plural': 'Detalles de Mantenimientos',
                'ordering': ['pk'],
            },
        ),
    ]
