# Generated by Django 3.1.6 on 2021-06-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0195_auto_20210620_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image_equipment',
            field=models.FileField(blank=True, default='Equipments/empty.png', null=True, upload_to='Equipments'),
        ),
        migrations.AddField(
            model_name='services',
            name='logo_business',
            field=models.FileField(blank=True, default='Logos/empty.png', null=True, upload_to='Logos'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='22:17:04 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-20 22:17:03 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
