# Generated by Django 3.1.6 on 2021-06-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0198_auto_20210623_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detmaintenance',
            name='april',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='august',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='december',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='february',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='january',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='july',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='june',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='march',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='may',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='november',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='october',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='september',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='01:41:43 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-23 01:41:43 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
