# Generated by Django 3.1.6 on 2021-06-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0199_auto_20210623_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detmaintenance',
            name='april',
            field=models.BooleanField(verbose_name='Abril'),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='august',
            field=models.BooleanField(verbose_name='Agosto'),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='december',
            field=models.BooleanField(verbose_name='Diciembre'),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='february',
            field=models.BooleanField(verbose_name='Febrero'),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='january',
            field=models.BooleanField(verbose_name='Enero'),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='july',
            field=models.BooleanField(verbose_name='Julio'),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='june',
            field=models.BooleanField(verbose_name='Junio'),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='march',
            field=models.BooleanField(verbose_name='Marzo'),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='may',
            field=models.BooleanField(verbose_name='Mayo'),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='november',
            field=models.BooleanField(verbose_name='Noviembre'),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='october',
            field=models.BooleanField(verbose_name='Octubre'),
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='september',
            field=models.BooleanField(verbose_name='Septiembre'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='01:44:32 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-23 01:44:32 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
