# Generated by Django 3.1.6 on 2021-06-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0200_auto_20210623_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='18:34:56 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-23 18:34:56 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
