# Generated by Django 3.1.6 on 2021-06-24 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0202_auto_20210623_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detmaintenance',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.charges', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='21:04:44 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-23 21:04:44 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
