# Generated by Django 3.1.6 on 2021-06-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0203_auto_20210623_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='21:05:09 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-23 21:05:09 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
