# Generated by Django 3.1.6 on 2021-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0204_auto_20210623_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='charge',
            field=models.CharField(max_length=255, unique=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='equipmentsbrand',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipmentsmodels',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='datejoined',
            field=models.DateField(default='2021-06-26', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-06-26', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='services',
            name='datejoined',
            field=models.DateField(default='2021-06-26', max_length=50, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='04:56:10 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_time',
            field=models.DateField(default='2021-06-26', max_length=50, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-26 04:56:01 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
