# Generated by Django 3.1.6 on 2021-06-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0206_auto_20210626_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='05:57:59 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-26 05:57:59 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
