# Generated by Django 3.1.6 on 2021-06-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0207_auto_20210626_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='period',
            new_name='timeFrame',
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='07:08:47 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-26 07:08:47 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
