# Generated by Django 3.1.6 on 2021-06-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0208_auto_20210626_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='business',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crud.business', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='08:36:41 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-26 08:36:40 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
