# Generated by Django 3.1.6 on 2021-06-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0210_auto_20210628_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentsummary',
            options={'ordering': ['pk'], 'verbose_name': 'Hoja de vida', 'verbose_name_plural': 'Hojas de vida'},
        ),
        migrations.AlterField(
            model_name='detmaintenance',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.maintenance'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='19:07:22 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-28 19:07:22 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
        migrations.CreateModel(
            name='DetEquipmentSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentName', models.CharField(max_length=150, verbose_name='Nombre')),
                ('componentBrand', models.CharField(max_length=150, verbose_name='Marca')),
                ('componentModel', models.CharField(max_length=150, verbose_name='Modelo')),
                ('componentSerie', models.CharField(max_length=150, verbose_name='Serial')),
                ('equipmentSummary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.equipmentsummary')),
            ],
            options={
                'verbose_name': 'Detalle de Componentes',
                'verbose_name_plural': 'Detalles de Componentes',
                'ordering': ['pk'],
            },
        ),
    ]
