# Generated by Django 3.1.6 on 2021-06-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0211_auto_20210628_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsummary',
            name='pressure_2',
            field=models.CharField(default=2, max_length=255, verbose_name='Presion (Psi)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentsummary',
            name='pressure',
            field=models.CharField(max_length=255, verbose_name='Presión (Psi)'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='19:57:13 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-28 19:57:13 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
