# Generated by Django 3.1.6 on 2021-06-29 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0212_auto_20210628_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsummary',
            name='business',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crud.business', verbose_name='Empresa/Centro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='20:49:44 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-28 20:49:43 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
