# Generated by Django 3.1.6 on 2021-06-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0213_auto_20210628_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsummary',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='20:52:34 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-28 20:52:34 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
