# Generated by Django 3.1.6 on 2021-06-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0214_auto_20210628_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsummary',
            name='fixedEquipment',
            field=models.BooleanField(default=False, verbose_name='Equipo Fijo'),
        ),
        migrations.AlterField(
            model_name='equipmentsummary',
            name='mobileEquipment',
            field=models.BooleanField(default=False, verbose_name='Equipo Móvil'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='22:35:39 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-06-28 22:35:39 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
