# Generated by Django 3.1.6 on 2021-07-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0215_auto_20210628_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsummary',
            name='forAnotherDescription',
            field=models.CharField(default=2, max_length=255, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='datejoined',
            field=models.DateField(default='2021-07-02', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-07-02', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='services',
            name='datejoined',
            field=models.DateField(default='2021-07-02', max_length=50, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='02:47:28 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_time',
            field=models.DateField(default='2021-07-02', max_length=50, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-02 02:47:22 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
