# Generated by Django 3.1.6 on 2021-07-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0216_auto_20210702_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsummary',
            name='rH',
            field=models.CharField(max_length=350, verbose_name='Humedad Relativa (%)'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='03:32:28 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-02 03:32:28 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
