# Generated by Django 3.1.6 on 2021-07-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0218_auto_20210702_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsummary',
            name='calibrationPeriod',
            field=models.CharField(choices=[('TRIMESTRAL', 'TRIMESTRAL'), ('SEMESTRAL', 'SEMESTRAL'), ('ANUAL', 'ANUAL')], default='TRIMESTRAL', max_length=50, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='equipmentsummary',
            name='maintenancePeriod',
            field=models.CharField(choices=[('TRIMESTRAL', 'TRIMESTRAL'), ('SEMESTRAL', 'SEMESTRAL'), ('ANUAL', 'ANUAL')], default='TRIMESTRAL', max_length=50, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='04:50:25 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-02 04:50:25 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
