# Generated by Django 3.1.6 on 2021-07-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0220_auto_20210702_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='05:16:39 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-02 05:16:39 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
