# Generated by Django 3.1.6 on 2021-07-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0221_auto_20210702_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsummary',
            name='datejoined',
            field=models.DateField(default='2021-07-02', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='09:17:48 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-02 09:17:48 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
