# Generated by Django 3.1.6 on 2021-07-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0222_auto_20210702_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de equipo',
                'verbose_name_plural': 'Tipo de equipo',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterField(
            model_name='equipmentsummary',
            name='datejoined',
            field=models.DateField(default='2021-07-05', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='datejoined',
            field=models.DateField(default='2021-07-05', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-07-05', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='services',
            name='datejoined',
            field=models.DateField(default='2021-07-05', max_length=50, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='14:31:41 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_time',
            field=models.DateField(default='2021-07-05', max_length=50, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-05 14:31:33 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('datejoined', models.DateField(default='2021-07-05', max_length=50, verbose_name='Fecha')),
                ('code', models.CharField(max_length=100, verbose_name='Código')),
                ('version', models.CharField(max_length=100, verbose_name='Versión')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.business', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Inventario',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='DetInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(default=0)),
                ('serial', models.CharField(max_length=100, verbose_name='Serial')),
                ('riskClassification', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('IIA', 'IIA'), ('IIB', 'IIB'), ('III', 'III')], default='I', max_length=20, verbose_name='Clasificación de Riesgo')),
                ('invimaRegistration', models.CharField(max_length=100, verbose_name='Registro Invima')),
                ('usefulLife', models.CharField(max_length=100, verbose_name='Vida útil')),
                ('lot', models.CharField(max_length=100, verbose_name='Lote')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación o servicio')),
                ('statusEquipment', models.CharField(choices=[('BUENO', 'BUENO'), ('REGULAR', 'REGULAR'), ('MALO', 'MALO')], default='BUENO', max_length=20, verbose_name='Estado del equipo')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipments', verbose_name='Equipo')),
                ('equipmentBrand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentsbrand', verbose_name='Marca')),
                ('equipmentModels', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentsmodels', verbose_name='Modelo')),
                ('equipmentType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentstype', verbose_name='Tipo')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.inventory')),
            ],
            options={
                'verbose_name': 'Detalle de inventario',
                'ordering': ['pk'],
            },
        ),
    ]
