# Generated by Django 3.1.6 on 2021-07-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0225_auto_20210705_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='16:21:14 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-05 16:21:14 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
