# Generated by Django 3.1.6 on 2021-07-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0226_auto_20210705_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detinventory',
            name='statusEquipment',
            field=models.CharField(choices=[('BUENO', 'BUENO'), ('MALO', 'MALO'), ('REGULAR', 'REGULAR')], default='BUENO', max_length=20, verbose_name='Estado del equipo'),
        ),
        migrations.AlterField(
            model_name='equipmentsummary',
            name='datejoined',
            field=models.DateField(default='2021-07-06', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='datejoined',
            field=models.DateField(default='2021-07-06', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='datejoined',
            field=models.DateField(default='2021-07-06', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-07-06', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='services',
            name='datejoined',
            field=models.DateField(default='2021-07-06', max_length=50, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='00:10:08 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_time',
            field=models.DateField(default='2021-07-06', max_length=50, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-06 00:10:08 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
