# Generated by Django 3.1.6 on 2021-07-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0227_auto_20210706_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='00:11:18 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-06 00:11:18 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
        migrations.DeleteModel(
            name='DetInventory',
        ),
    ]
