# Generated by Django 3.1.6 on 2021-07-06 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0228_auto_20210706_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='00:13:09 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-06 00:13:09 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
        migrations.CreateModel(
            name='DetInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(default=0)),
                ('serial', models.CharField(max_length=100, verbose_name='Serial')),
                ('riskClassification', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('IIA', 'IIA'), ('IIB', 'IIB'), ('III', 'III')], default='I', max_length=20, verbose_name='Clasificación de Riesgo')),
                ('invimaRegistration', models.CharField(max_length=100, verbose_name='Registro Invima')),
                ('usefulLife', models.CharField(max_length=100, verbose_name='Vida útil')),
                ('lot', models.CharField(max_length=100, verbose_name='Lote')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación o servicio')),
                ('statusEquipment', models.CharField(choices=[('BUENO', 'BUENO'), ('MALO', 'MALO'), ('REGULAR', 'REGULAR')], default='BUENO', max_length=20, verbose_name='Estado del equipo')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipments', verbose_name='Equipo')),
                ('equipmentBrand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentsbrand', verbose_name='Marca')),
                ('equipmentModels', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentsmodels', verbose_name='Modelo')),
                ('equipmentType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentstype', verbose_name='Tipo')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.inventory')),
            ],
            options={
                'verbose_name': 'Detalle de inventario',
                'ordering': ['pk'],
            },
        ),
    ]
