# Generated by Django 3.1.6 on 2021-07-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0229_auto_20210706_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySedes',
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['pk'], 'verbose_name': 'Productos y Servicios'},
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='rif',
        ),
        migrations.RemoveField(
            model_name='services',
            name='business',
        ),
        migrations.RemoveField(
            model_name='services',
            name='consecutive',
        ),
        migrations.RemoveField(
            model_name='services',
            name='datejoined',
        ),
        migrations.RemoveField(
            model_name='services',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='services',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_anomaly',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_brand',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_date',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_location',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_model',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_others',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_received',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_reference',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_reported',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_serie',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_service',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_work_hours',
        ),
        migrations.RemoveField(
            model_name='services',
            name='image_equipment',
        ),
        migrations.RemoveField(
            model_name='services',
            name='logo_business',
        ),
        migrations.RemoveField(
            model_name='services',
            name='number_version',
        ),
        migrations.RemoveField(
            model_name='services',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='services',
            name='report_number',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_details',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_received',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_reported',
        ),
        migrations.RemoveField(
            model_name='services',
            name='spare_parts',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(default=2, max_length=225, verbose_name='Dirección Fiscal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(default=2, max_length=225, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.CharField(default=2, max_length=255, verbose_name='Correo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='nit',
            field=models.CharField(default=2, max_length=225, verbose_name='NIT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default=2, max_length=255, verbose_name='Telefono(s)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='services',
            field=models.TextField(default=2, verbose_name='Servicios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='count',
            field=models.BooleanField(default=False, verbose_name='Añadir inventario'),
        ),
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='services',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='service',
            field=models.CharField(default=2, max_length=255, verbose_name='Servicio/Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentsummary',
            name='datejoined',
            field=models.DateField(default='2021-07-07', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='datejoined',
            field=models.DateField(default='2021-07-07', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='datejoined',
            field=models.DateField(default='2021-07-07', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-07-07', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='services',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Código'),
        ),
    ]
