# Generated by Django 3.1.6 on 2021-07-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0230_auto_20210707_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsAndServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Código')),
                ('service', models.CharField(max_length=255, verbose_name='Servicio/Producto')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Costo')),
                ('count', models.BooleanField(default=False, verbose_name='Añadir inventario')),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Productos y Servicios',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='count',
        ),
        migrations.RemoveField(
            model_name='services',
            name='price',
        ),
        migrations.RemoveField(
            model_name='services',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service',
        ),
        migrations.AddField(
            model_name='services',
            name='business',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crud.business', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='consecutive',
            field=models.CharField(default='000', max_length=255, verbose_name='Secuencia'),
        ),
        migrations.AddField(
            model_name='services',
            name='datejoined',
            field=models.DateField(default='2021-07-07', max_length=50, verbose_name='Fecha actualización'),
        ),
        migrations.AddField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='05:24:00 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AddField(
            model_name='services',
            name='delivery_time',
            field=models.DateField(default='2021-07-07', max_length=50, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='services',
            name='equipment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crud.equipments', verbose_name='Equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_anomaly',
            field=models.TextField(default=2, verbose_name='Anomalía'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_brand',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentsbrand', verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-07 05:24:00 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_location',
            field=models.CharField(default=2, max_length=250, verbose_name='Ubicación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_model',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crud.equipmentsmodels', verbose_name='Modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_others',
            field=models.CharField(default=2, max_length=250, verbose_name='Otros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_received',
            field=models.CharField(default=2, max_length=255, verbose_name='Recibido por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_reference',
            field=models.CharField(default=2, max_length=250, verbose_name='Referencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_reported',
            field=models.CharField(default=2, max_length=255, verbose_name='Reportado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_serie',
            field=models.CharField(default=2, max_length=250, verbose_name='Serie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_service',
            field=models.CharField(choices=[('PREVENTIVO', 'PREVENTIVO'), ('CORRECTIVO', 'CORRECTIVO')], default='PREVENTIVO', max_length=20, verbose_name='Tipo de Mantenimiento'),
        ),
        migrations.AddField(
            model_name='services',
            name='equipment_work_hours',
            field=models.CharField(default=2, max_length=250, verbose_name='Horas Trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='image_equipment',
            field=models.FileField(blank=True, default='Equipments/empty.png', null=True, upload_to='Equipments'),
        ),
        migrations.AddField(
            model_name='services',
            name='logo_business',
            field=models.FileField(blank=True, default='Logos/empty.png', null=True, upload_to='Logos'),
        ),
        migrations.AddField(
            model_name='services',
            name='number_version',
            field=models.CharField(default=2, max_length=250, verbose_name='Version Nº'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='observations',
            field=models.TextField(default=2, verbose_name='Observaciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='report_number',
            field=models.CharField(default='000', max_length=255, verbose_name='Consecutivo'),
        ),
        migrations.AddField(
            model_name='services',
            name='service_details',
            field=models.TextField(default=2, verbose_name='Detalles del Servicio Técnico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='service_received',
            field=models.CharField(default=2, max_length=255, verbose_name='Recibido por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='service_reported',
            field=models.CharField(default=2, max_length=255, verbose_name='Reportado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='spare_parts',
            field=models.TextField(default=2, verbose_name='Repuestos utilizados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='code',
            field=models.CharField(max_length=250, verbose_name='Código'),
        ),
    ]
