# Generated by Django 3.1.6 on 2021-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0239_auto_20210707_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='12:26:30 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-07 12:26:30 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
