# Generated by Django 3.1.6 on 2021-07-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0240_auto_20210707_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsandservices',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='13:18:59 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-07 13:18:52 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
