# Generated by Django 3.1.6 on 2021-07-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0243_auto_20210707_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsandservices',
            name='image',
            field=models.FileField(blank=True, default='img/products/default.png', null=True, upload_to='img/products', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='16:44:26 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-07 16:44:26 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
