# Generated by Django 3.1.6 on 2021-07-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0244_auto_20210707_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsandservices',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='16:45:21 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-07 16:45:21 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
