# Generated by Django 3.1.6 on 2021-07-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0247_auto_20210707_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesandquotes',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='20:10:23 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-07 20:10:23 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
