# Generated by Django 3.1.6 on 2021-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0251_auto_20210708_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesandquotes',
            name='number_invoice',
            field=models.CharField(default=0, max_length=255, verbose_name='Nº Factura'),
        ),
        migrations.AlterField(
            model_name='invoicesandquotes',
            name='number_quotes',
            field=models.CharField(default=0, max_length=255, verbose_name='Nº Cotización'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='08:17:44 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-08 08:17:44 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
