# Generated by Django 3.1.6 on 2021-07-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0254_auto_20210708_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesandquotes',
            name='status',
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='17:09:31 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-08 17:09:31 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
