# Generated by Django 3.1.6 on 2021-07-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0255_auto_20210708_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Evento')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('day', models.DateField(default='2021-07-08', max_length=50, verbose_name='Fecha')),
                ('color', models.CharField(default='#007bff', max_length=250, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Eventos',
                'verbose_name_plural': 'Eventos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='20:50:29 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-08 20:50:29 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
