# Generated by Django 3.1.6 on 2021-07-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0261_auto_20210710_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='13:24:06 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-10 13:24:05 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image_equipment',
            field=models.FileField(blank=True, default='Equipments/empty.png', null=True, upload_to='Equipments', verbose_name='Imagen del equipo'),
        ),
    ]
