# Generated by Django 3.1.6 on 2021-07-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0262_auto_20210710_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='report_number',
        ),
        migrations.AddField(
            model_name='services',
            name='year',
            field=models.CharField(default=2, max_length=255, verbose_name='Año'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='code',
            field=models.CharField(default='FO-MH-001', max_length=250, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='services',
            name='datejoined',
            field=models.DateField(default='10/07/2021', max_length=50, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='13:41:26 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-10 13:41:26 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='services',
            name='number_version',
            field=models.CharField(default='2', max_length=250, verbose_name='Version Nº'),
        ),
    ]
