# Generated by Django 3.1.6 on 2021-07-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0263_auto_20210710_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='datejoined',
            field=models.CharField(default='10/07/2021', max_length=50, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='13:43:56 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-10 13:43:56 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
