# Generated by Django 3.1.6 on 2021-07-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0266_auto_20210710_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, default='logos/empty.png', null=True, upload_to='img/logos', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='23:36:21 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-10 23:36:21 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
