# Generated by Django 3.1.6 on 2021-07-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0271_auto_20210720_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='code',
            field=models.CharField(default='FO-MAN-002', max_length=255, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='version',
            field=models.CharField(default='2 10-07-2021', max_length=250, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='00:26:33 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-20 00:26:33 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
