# Generated by Django 3.1.6 on 2021-07-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0272_auto_20210720_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='17:02:20 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-20 17:02:20 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
