# Generated by Django 3.1.6 on 2021-07-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0275_auto_20210721_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detmaintenance',
            name='period',
            field=models.CharField(choices=[('NO APLICA', 'NO APLICA'), ('TRIMESTRAL', 'TRIMESTRAL'), ('SEMESTRAL', 'SEMESTRAL'), ('ANUAL', 'ANUAL')], default='TRIMESTRAL', max_length=50, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='equipmentsummary',
            name='calibrationPeriod',
            field=models.CharField(choices=[('NO APLICA', 'NO APLICA'), ('TRIMESTRAL', 'TRIMESTRAL'), ('SEMESTRAL', 'SEMESTRAL'), ('ANUAL', 'ANUAL')], default='TRIMESTRAL', max_length=50, verbose_name='Periocidad calibración metrológico (meses)'),
        ),
        migrations.AlterField(
            model_name='equipmentsummary',
            name='datejoined',
            field=models.DateField(default='2021-07-30', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='equipmentsummary',
            name='maintenancePeriod',
            field=models.CharField(choices=[('NO APLICA', 'NO APLICA'), ('TRIMESTRAL', 'TRIMESTRAL'), ('SEMESTRAL', 'SEMESTRAL'), ('ANUAL', 'ANUAL')], default='NO APLICA', max_length=50, verbose_name='Periocidad mantenimiento preventivo (meses)'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2021-07-30', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='datejoined',
            field=models.DateField(default='2021-07-30', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='invoicesandquotes',
            name='datejoined',
            field=models.DateField(default='30-07-2021', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='datejoined',
            field=models.DateField(default='2021-07-30', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-07-30', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='services',
            name='dateRegister',
            field=models.DateField(default='2021-07-30', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='23:39:47 PM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_time',
            field=models.DateField(default='2021-07-30', max_length=50, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-07-30 23:39:47 PM', max_length=50, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_service',
            field=models.CharField(choices=[('NO', 'NO'), ('PREVENTIVO', 'PREVENTIVO'), ('CORRECTIVO', 'CORRECTIVO')], default='NO', max_length=20, verbose_name='Tipo de Mantenimiento'),
        ),
    ]
