# Generated by Django 3.1.6 on 2021-08-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0277_auto_20210731_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsummary',
            name='datejoined',
            field=models.DateField(default='2021-08-01', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2021-08-01', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='code',
            field=models.CharField(default='FO-INV-001', max_length=255, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='datejoined',
            field=models.DateField(default='2021-08-01', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='version',
            field=models.CharField(default='2 10-07-2021', max_length=250, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='invoicesandquotes',
            name='datejoined',
            field=models.DateField(default='01-08-2021', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='datejoined',
            field=models.DateField(default='2021-08-01', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2021-08-01', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='services',
            name='dateRegister',
            field=models.DateField(default='2021-08-01', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='00:59:49 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_time',
            field=models.DateField(default='2021-08-01', max_length=50, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-08-01 00:59:49 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
