# Generated by Django 3.1.6 on 2021-08-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0278_auto_20210801_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detmaintenance',
            name='period',
            field=models.CharField(choices=[('NO APLICA', 'NO APLICA'), ('TRIMESTRAL', 'TRIMESTRAL'), ('SEMESTRAL', 'SEMESTRAL'), ('ANUAL', 'ANUAL')], default='TRIMESTRAL', max_length=50, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='01:11:39 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-08-01 01:11:39 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
