# Generated by Django 3.1.6 on 2021-08-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0279_auto_20210801_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='detmaintenance',
            name='invimaRegistration',
            field=models.CharField(default=2, max_length=100, verbose_name='Registro Invima'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detmaintenance',
            name='lot',
            field=models.CharField(default=2, max_length=100, verbose_name='Lote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detmaintenance',
            name='riskClassification',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('IIA', 'IIA'), ('IIB', 'IIB'), ('III', 'III')], default='I', max_length=20, verbose_name='Clasificación de Riesgo'),
        ),
        migrations.AddField(
            model_name='detmaintenance',
            name='usefulLife',
            field=models.CharField(default=2, max_length=100, verbose_name='Vida útil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='01:13:47 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-08-01 01:13:47 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
