# Generated by Django 3.1.6 on 2021-08-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0280_auto_20210801_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesandquotes',
            name='retefuente',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=30, verbose_name='Retefuente'),
        ),
        migrations.AddField(
            model_name='invoicesandquotes',
            name='retefuente_percentage',
            field=models.CharField(default=0, max_length=5, verbose_name='Retefuente %'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicesandquotes',
            name='discount_percentage',
            field=models.CharField(max_length=5, verbose_name='Descuento %'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_date',
            field=models.CharField(default='03:17:52 AM', max_length=250, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='services',
            name='equipment_date',
            field=models.CharField(default='2021-08-01 03:17:52 AM', max_length=50, verbose_name='Fecha y Hora'),
        ),
    ]
