# Generated by Django 3.1.6 on 2022-10-25 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0282_auto_20221021_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre/Razon Social')),
                ('identity', models.CharField(choices=[('V', 'V'), ('J', 'J'), ('E', 'E'), ('G', 'G'), ('FP', 'FP')], max_length=3, verbose_name='Tipo')),
                ('dni', models.CharField(max_length=200, verbose_name='CI/RIF')),
                ('address', models.CharField(max_length=225, verbose_name='Dirección')),
                ('town', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('township', models.CharField(max_length=100, verbose_name='Municipio')),
                ('postalZone', models.CharField(max_length=10, verbose_name='Zona Postal')),
                ('houseNumber', models.CharField(max_length=10, verbose_name='Casa/Local/Nº')),
                ('phone', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=100, verbose_name='Correo')),
                ('coordinates', models.CharField(default=0, max_length=225, verbose_name='Coordenadas')),
                ('aboutCompany', models.CharField(choices=[('Recomendación', 'Recomendacion'), ('Radio', 'Radio'), ('Oficina', 'Oficina'), ('Página Internet', 'Página Internet'), ('Redes Sociales', 'Redes Sociales'), ('Otros', 'Otros')], max_length=30, verbose_name='¿Cómo conoció la empresa?')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Zona')),
                ('description', models.CharField(max_length=225, verbose_name='Descripción')),
                ('coordinates', models.CharField(max_length=225, verbose_name='Coordenadas')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveField(
            model_name='detequipmentsummary',
            name='equipmentSummary',
        ),
        migrations.RemoveField(
            model_name='detinventory',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='detinventory',
            name='equipmentBrand',
        ),
        migrations.RemoveField(
            model_name='detinventory',
            name='equipmentModels',
        ),
        migrations.RemoveField(
            model_name='detinventory',
            name='equipmentType',
        ),
        migrations.RemoveField(
            model_name='detinventory',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='detinvoicesandquotes',
            name='invoicesAndQuotes',
        ),
        migrations.RemoveField(
            model_name='detmaintenance',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='detmaintenance',
            name='equipmentBrand',
        ),
        migrations.RemoveField(
            model_name='detmaintenance',
            name='equipmentModels',
        ),
        migrations.RemoveField(
            model_name='detmaintenance',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='detmaintenance',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='equipmentsummary',
            name='business',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='business',
        ),
        migrations.RemoveField(
            model_name='invoicesandquotes',
            name='business',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='business',
        ),
        migrations.DeleteModel(
            name='ProductsAndServices',
        ),
        migrations.RemoveField(
            model_name='services',
            name='business',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_brand',
        ),
        migrations.RemoveField(
            model_name='services',
            name='equipment_model',
        ),
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2022-10-24', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2022-10-24', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.DeleteModel(
            name='DetEquipmentSummary',
        ),
        migrations.DeleteModel(
            name='DetInventory',
        ),
        migrations.DeleteModel(
            name='DetInvoicesAndQuotes',
        ),
        migrations.DeleteModel(
            name='DetMaintenance',
        ),
        migrations.DeleteModel(
            name='EquipmentSummary',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InvoicesAndQuotes',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AddField(
            model_name='client',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.zone', verbose_name='Zona'),
        ),
    ]
