# Generated by Django 3.1.6 on 2022-11-03 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0283_auto_20221024_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Costo')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Costo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre/Razon Social')),
                ('identity', models.CharField(choices=[('V', 'V'), ('J', 'J'), ('E', 'E'), ('G', 'G'), ('FP', 'FP')], max_length=3, verbose_name='Tipo')),
                ('dni', models.CharField(max_length=200, verbose_name='CI')),
                ('charge', models.CharField(max_length=200, verbose_name='Cargo')),
                ('address', models.CharField(max_length=225, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=100, verbose_name='Correo')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2022-11-03', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2022-11-03', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='00000000', max_length=8, verbose_name='Nº Instalación')),
                ('installationDate', models.DateField(default='2022-11-03', max_length=10, verbose_name='Fecha de instalación')),
                ('payday', models.DateField(default='2022-11-03', max_length=10, verbose_name='Fecha de pago')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Monto cancelado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.client', verbose_name='Cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.plan', verbose_name='Plan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.service', verbose_name='Servicio')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.technician', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='00000000', max_length=8, verbose_name='Nº Inspección')),
                ('inspectionDate', models.DateField(default='2022-11-03', max_length=10, verbose_name='Fecha de inspección')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.client', verbose_name='Cliente')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.technician', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectionQueue', models.CharField(max_length=255, verbose_name='Queue')),
                ('connectionIp', models.CharField(max_length=255, verbose_name='Ip')),
                ('connectionMac', models.CharField(max_length=255, verbose_name='Mac')),
                ('connectionCpe', models.CharField(max_length=255, verbose_name='Cpe')),
                ('connectionRouter', models.CharField(max_length=255, verbose_name='Router')),
                ('antennaModel', models.CharField(max_length=255, verbose_name='Modelo de Antena')),
                ('antennaUser', models.CharField(max_length=255, verbose_name='Usuario de Antena')),
                ('antennaPassword', models.CharField(max_length=255, verbose_name='Contraseña de Antena')),
                ('connectionProtocol', models.CharField(max_length=255, verbose_name='Protocolo de Conexión')),
                ('snONU', models.CharField(max_length=255, verbose_name='SN ONU')),
                ('routerIp', models.CharField(max_length=255, verbose_name='IP router')),
                ('routerModel', models.CharField(max_length=255, verbose_name='Modelo de Router')),
                ('routerUser', models.CharField(max_length=255, verbose_name='Usuario del Router')),
                ('routerPassword', models.CharField(max_length=255, verbose_name='Contraseña del Router')),
                ('routerWifiSSID', models.CharField(max_length=255, verbose_name='SSID Wifi Router')),
                ('routerWifiPassword', models.CharField(max_length=255, verbose_name='Password Wifi Router')),
                ('routerMAC', models.CharField(max_length=255, verbose_name='MAC Router')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Detalle de Conexion del Cliente',
                'verbose_name_plural': 'Detalles de conexión de Clientes',
                'ordering': ['pk'],
            },
        ),
    ]
