# Generated by Django 3.1.6 on 2023-01-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0284_auto_20221103_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Charges',
        ),
        migrations.DeleteModel(
            name='Equipments',
        ),
        migrations.DeleteModel(
            name='EquipmentsBrand',
        ),
        migrations.DeleteModel(
            name='EquipmentsModels',
        ),
        migrations.DeleteModel(
            name='EquipmentsType',
        ),
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2023-01-28', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspectionDate',
            field=models.DateField(default='2023-01-28', max_length=10, verbose_name='Fecha de inspección'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='installationDate',
            field=models.DateField(default='2023-01-28', max_length=10, verbose_name='Fecha de instalación'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='payday',
            field=models.DateField(default='2023-01-28', max_length=10, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2023-01-28', max_length=50, verbose_name='Fecha de pago'),
        ),
    ]
