# Generated by Django 3.1.6 on 2023-01-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0286_auto_20230130_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='comercialName',
            field=models.CharField(default=1, max_length=225, verbose_name='Nombre Comercial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/logo'),
        ),
    ]
