# Generated by Django 3.1.6 on 2023-01-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0287_auto_20230130_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['id'],
            },
        ),
    ]
