# Generated by Django 3.1.6 on 2023-01-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0289_dolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['id'],
            },
        ),
    ]
