# Generated by Django 3.1.6 on 2023-01-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0290_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['id'],
            },
        ),
    ]
