# Generated by Django 3.1.6 on 2023-01-31 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0291_type_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='Código')),
                ('product', models.CharField(max_length=150, verbose_name='Producto')),
                ('brand', models.CharField(max_length=150, verbose_name='Marca')),
                ('description', models.CharField(max_length=180, verbose_name='Descripción')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio|Costo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio sin IVA')),
                ('price_dl', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio|Venta')),
                ('gain', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Ganancia')),
                ('price_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Bs.')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cantidad')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.category', verbose_name='Categoría')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.type_product', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Producto (Ventas)',
                'verbose_name_plural': 'Productos (Ventas)',
                'ordering': ['id'],
            },
        ),
    ]
