# Generated by Django 3.1.6 on 2023-01-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0292_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Cliente')),
                ('identity', models.CharField(choices=[('V', 'V'), ('J', 'J'), ('E', 'E'), ('G', 'G'), ('FP', 'FP')], default='V', max_length=3, verbose_name='Identificación')),
                ('ci', models.CharField(max_length=50, unique=True, verbose_name='CI/RIF')),
                ('address', models.CharField(max_length=180, verbose_name='Dirección')),
                ('contact', models.CharField(max_length=50, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
