# Generated by Django 3.1.6 on 2023-01-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0293_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method_pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Método de Pago')),
                ('type_symbol', models.CharField(choices=[('Bs', 'Bs'), ('$', '$')], default='$', max_length=3, verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['id'],
            },
        ),
    ]
