# Generated by Django 3.1.6 on 2023-01-31 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0294_method_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_credit_date', models.DateField(default='2023-01-31', max_length=10, verbose_name='Fecha')),
                ('totalDebt', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.client')),
            ],
            options={
                'verbose_name': 'Venta a Crédito',
                'verbose_name_plural': 'Ventas a Crédito',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2023-01-31', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2023-01-31', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='NA', max_length=255, verbose_name='Vendedor')),
                ('datejoined', models.DateField(default='2023-01-31', max_length=10, verbose_name='Fecha')),
                ('invoice_number', models.CharField(default='00000000', max_length=255, verbose_name='Nº Factura')),
                ('control_number', models.CharField(default='00000000', max_length=255, verbose_name='Nº de Control')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Subtotal $')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Descuento $')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='IVA 16%')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total $')),
                ('type_sale', models.CharField(max_length=25, verbose_name='Método')),
                ('received', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Entrada (1)')),
                ('received1', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Entrada (2)')),
                ('received2', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Entrada (3)')),
                ('discountChange', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Vuelto descontado')),
                ('pendingChange', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Vuelto pendiente')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('status', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.client')),
                ('method_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_pays', to='crud.method_pay', verbose_name='Método de pago (1)')),
                ('method_pay1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_pays1', to='crud.method_pay', verbose_name='Método de pago (2)')),
                ('method_pay2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_pays2', to='crud.method_pay', verbose_name='Método de pago (3)')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PendingChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_credit_date', models.DateField(default='2023-01-31', max_length=10, verbose_name='Fecha')),
                ('totalChange', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.client')),
            ],
            options={
                'verbose_name': 'Venta a Crédito',
                'verbose_name_plural': 'Ventas a Crédito',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio Producto $')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Tasa $')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetPendingChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(default='+', max_length=2, verbose_name='Operación')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cantidad')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('pendingChange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.pendingchanges')),
            ],
            options={
                'verbose_name': 'Detalle del Vuelto Pendiente',
                'verbose_name_plural': 'Detalle de Vueltos Pendientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(default='+', max_length=2, verbose_name='Operación')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cantidad')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.credit')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.sale')),
            ],
            options={
                'verbose_name': 'Detalle del Crédito',
                'verbose_name_plural': 'Detalle de Créditos',
                'ordering': ['id'],
            },
        ),
    ]
