# Generated by Django 3.1.6 on 2023-01-31 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0295_auto_20230131_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_number', models.CharField(default='00000000', max_length=255, verbose_name='Presupuesto Nº')),
                ('datejoined', models.DateField(default='2023-01-31', max_length=10, verbose_name='Fecha')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Subtotal $')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Descuento $')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='IVA 16%')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total $')),
                ('type_sale', models.CharField(max_length=25, verbose_name='Presupuesto')),
                ('description', models.CharField(max_length=250, verbose_name='Nota')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.client')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Precio Producto $')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total')),
                ('rate', models.DecimalField(decimal_places=22, default=0.0, max_digits=30, verbose_name='Tasa $ Calculada')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.budget')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.product')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto',
                'verbose_name_plural': 'Detalle de Presupuestos',
                'ordering': ['id'],
            },
        ),
    ]
