# Generated by Django 3.1.6 on 2023-02-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0296_budget_detbudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discountChange',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='pendingChange',
        ),
        migrations.AlterField(
            model_name='budget',
            name='datejoined',
            field=models.DateField(default='2023-02-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='last_credit_date',
            field=models.DateField(default='2023-02-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2023-02-01', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='pendingchanges',
            name='last_credit_date',
            field=models.DateField(default='2023-02-01', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2023-02-01', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2023-02-01', max_length=10, verbose_name='Fecha'),
        ),
    ]
