# Generated by Django 3.1.6 on 2023-02-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0297_auto_20230201_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='totalBs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total Bs'),
        ),
    ]
