# Generated by Django 3.1.6 on 2023-02-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0298_sale_totalbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='Notas'),
            preserve_default=False,
        ),
    ]
