# Generated by Django 3.1.6 on 2023-02-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0300_auto_20230203_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='datehour',
            field=models.CharField(default='2023-02-03', max_length=30, verbose_name='Fecha'),
        ),
    ]
