# Generated by Django 3.1.6 on 2023-02-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0304_auto_20230205_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.CharField(default='NA', max_length=255, verbose_name='Vendedor'),
        ),
    ]
