# Generated by Django 3.1.6 on 2023-02-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0310_auto_20230212_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
