# Generated by Django 3.1.6 on 2023-02-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0311_debt_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='totalDebt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Total $'),
        ),
    ]
