# Generated by Django 3.1.6 on 2025-03-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0317_auto_20240322_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='datejoined',
            field=models.DateField(default='2025-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='datehour',
            field=models.CharField(default='2025-03-21', max_length=30, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='last_credit_date',
            field=models.DateField(default='2025-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='datehour',
            field=models.CharField(default='2025-03-21', max_length=30, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='last_credit_date',
            field=models.DateField(default='2025-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='detcredit',
            name='datehour',
            field=models.CharField(default='2025-03-21', max_length=30, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='detcredit',
            name='last_credit_date',
            field=models.DateField(default='2025-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='detdebt',
            name='datehour',
            field=models.CharField(default='2025-03-21', max_length=30, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='detdebt',
            name='last_debt_date',
            field=models.DateField(default='2025-03-21', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2025-03-21', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2025-03-21', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datehour',
            field=models.CharField(default='2025-03-21', max_length=30, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2025-03-21', max_length=10, verbose_name='Fecha'),
        ),
    ]
