# Generated by Django 3.1.6 on 2026-05-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0321_auto_20260502_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='detcredit',
            name='method_pay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crud.method_pay', verbose_name='Método de pago'),
            preserve_default=False,
        ),
    ]
