# Generated by Django 3.1.6 on 2026-05-02 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0322_detcredit_method_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='detcredit',
            name='datehour2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detcredit',
            name='datehour',
            field=models.CharField(default='2026-05-02 04:48:49', max_length=30, verbose_name='Fecha y Hora'),
        ),
    ]
