# Generated by Django 3.1.6 on 2026-05-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0323_auto_20260502_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detcredit',
            name='datehour2',
        ),
        migrations.AlterField(
            model_name='detcredit',
            name='datehour',
            field=models.CharField(default='2026-05-02', max_length=30, verbose_name='Fecha y Hora'),
        ),
    ]
