# Generated by Django 3.1.6 on 2026-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0324_auto_20260502_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='detcredit',
            name='quantitybs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='CantidadBs'),
        ),
    ]
