# Generated by Django 3.1.6 on 2026-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0325_detcredit_quantitybs'),
    ]

    operations = [
        migrations.AddField(
            model_name='detcredit',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
