# Generated by Django 3.1.6 on 2026-05-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0327_auto_20260517_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
