# Generated by Django 3.1.6 on 2026-05-18 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0328_auto_20260517_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
