# Generated by Django 3.1.6 on 2026-05-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0329_remove_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
