# Generated by Django 3.1.6 on 2026-06-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0333_auto_20260609_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='amount_bs',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='amount_dl',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Cantidad dólares'),
        ),
    ]
